services:
  postgres:
    image: postgres:16
    container_name: webhookrelay_db
    restart: always
    environment:
      POSTGRES_USER: webhookuser
      POSTGRES_PASSWORD: webhookpass
      POSTGRES_DB: webhookrelay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
